from __future__ import annotations

from typing import Any, Iterable, Protocol

from .schemas import AudioChunk, SttResult, TtsChunk


class BaseVoiceService(Protocol):
    def initialize(self) -> None: ...
    def close(self) -> None: ...
    def health_check(self) -> dict[str, Any]: ...
    def collect_metrics(self) -> dict[str, Any]: ...


class SpeechToTextService(BaseVoiceService, Protocol):
    def accept_audio(self, chunk: AudioChunk) -> None: ...
    def poll_result(self) -> list[SttResult]: ...
    def reset(self) -> None: ...


class TextToSpeechService(BaseVoiceService, Protocol):
    @property
    def sample_rate(self) -> int: ...

    def synthesize_stream(self, text: str) -> Iterable[TtsChunk]: ...
    def stop(self) -> None: ...

